PygmentsCodeFences = true
baseurl         = "https://www.mlynn.org"
canonifyurls = true
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."
disqusShortname = "mlynn-1"
enableRobotsTXT = true
googleAnalytics = "UA-13067313-1"
languageCode = "en"
publishDir = "../hosting/files"
theme = "hugo-nuo"
title = "Michael Lynn"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 6
[[menu.main]]
identifier = "works"
name = "Works"
url = "https://github.com/mrlynn"
weight = 4

[params]
author = "mlynn"
avatar = "images/avatar.png"
bg = "images/grey-prism.svg"
changyan = false
changyanConf = ""
changyanId = ""
description = "Who Writes, Codes, Lifts, Runs, Recovers, Fathers, Meditates, Prays, and Helps Others? This guy."
email = "merlynn@gmail.com"
github = "mrlynn"
googleSiteVerification = ""
linkedin = "mlynn"
msValidate = ""
paginate = 10
seotitle = "Michael Lynn, Developer Advocate"
subtitle = "How can I help you?"
twitter = "mlynn"
wechat = ""
weibo = ""
